Don’t panic on errors
This patch uses the anyhow::Context trait to replace unwrap/expect with
more helpful anyhow errors.  For example, if the editor does not exist,
we now get:

    Error: Failed to execute editor process

    Caused by:
        No such file or directory (os error 2)

instead of:

    thread 'main' panicked at 'failed to execute process: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:85:14
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace